<?php

namespace AppBundle\Repository;

/**
 * CropTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CropTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
