<?php

namespace AppBundle\Repository;

/**
 * TractorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TractorRepository extends \Doctrine\ORM\EntityRepository
{
}
